parameters:
  role:
    type: string
steps:
  - aws-cli/install
  - aws-cli/configure
  - run:
      name: Assuming Role
      command: |
        temp_role=$(aws sts assume-role --role-arn << parameters.role >> --role-session-name "circle-assumed")
        echo "export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId -r)" >> $BASH_ENV
        echo "export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey -r)" >> $BASH_ENV
        echo "export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken -r)" >> $BASH_ENV
