description: merge merge_branch into base_branch
parameters:
  base_branch:
    type: string
  merge_branch:
    type: string
  tag:
    type: string
    default: "${RELEASE_VERSION}"
  trigger_ci:
    type: boolean
    default: true
  simulate:
    type: boolean
    default: false
steps:
  - run:
      name: merge to '<< parameters.base_branch >>'
      command: |
        echo "merging << parameters.merge_branch >> into '<< parameters.base_branch >>'"
        git fetch --all
        git checkout "<< parameters.merge_branch >>" && git pull
        git checkout "<< parameters.base_branch >>" && git pull

        merge_args="--no-verify --no-ff -m 'chore(release): merge << parameters.tag >>'"

        case << parameters.trigger_ci >> in
          false) merge_args="$merge_args -m '[ci skip]'";;
        esac

        case << parameters.simulate >> in
          true) merge_args="--no-commit $merge_args" ;;
        esac

        echo "merging - [git merge $merge_args << parameters.merge_branch >>]"
        result=$(git merge $merge_args "<< parameters.merge_branch >>" || echo "[merge-failed]")        
        if [[ "$result" =~ \[merge-failed\] ]]; then
          echo $result
          git status
          git reset --hard
          exit 1
        fi

        git push
