description: merge merge_branch into base_branch
parameters:
  base_branch:
    type: string
  merge_branch:
    type: string
  tag:
    type: string
    default: "${RELEASE_VERSION}"
  trigger_ci:
    type: boolean
    default: true
  simulate:
    type: boolean
    default: false
steps:
  - run:
      name: merge to '<< parameters.base_branch >>'
      command: |
        ./scripts/ci-merge-branch.sh \
            --base=<< parameters.base_branch >> \
            --merge=<< parameters.merge_branch >> \
            --simulate=<< parameters.simulate >> \
            --trigger=<< parameters.trigger_ci >> \
            --tag=<< parameters.tag >>
