executor: node
parameters:
  environment:
    type: string

steps:
  - attach_workspace:
      at: ./
  - run:
      name: deploy infrastructure [<< parameters.environment >>]
      command: echo "[simulation] deploying infrastructure..."
