executor: node
steps:
  - attach_workspace:
      at: ./
  - run:
      name: assert code formatting standards
      command: yarn fmt:diff
  - run:
      name: audit solution dependency security issues
      command: yarn audit --level moderate
