executor: node
parameters:
  production_branch:
    type: string
    default: "master"

steps:
  - attach_workspace:
      at: ./

  - git-set-identity

  - checkout

  - run:
      name: set release info
      # we *assume* this job is run from within the subject release branch
      command: |
        echo "export RELEASE_BRANCH_NAME=$CIRCLE_BRANCH" >> $BASH_ENV
        echo "export RELEASE_VERSION=$(cat package.json | jq -r .version)" >> $BASH_ENV

  - git-merge-branch:
      base_branch: "develop"
      merge_branch: "$RELEASE_BRANCH_NAME"
      simulate: true

  - git-merge-branch:
      base_branch: "master"
      merge_branch: "$RELEASE_BRANCH_NAME"
      simulate: true

  - git-merge-branch:
      base_branch: "develop"
      merge_branch: "$RELEASE_BRANCH_NAME"
      trigger_ci: false

  - git-merge-branch:
      base_branch: "master"
      merge_branch: "$RELEASE_BRANCH_NAME"

  - run:
      name: tag release
      command: |
        git branch
        git remote -v 

        git branch -r

        git fetch --all 

        if [[ -z $(git tag -l "v${RELEASE_VERSION}") ]]; then
          echo "tagging release v${RELEASE_VERSION} ..."
          git tag "v${RELEASE_VERSION}"
          git push --tags
        fi

  - run:
      name: remove release branch
      command: |
        git branch -D "$RELEASE_BRANCH_NAME"
        git push origin master --delete "$RELEASE_BRANCH_NAME" -m "[ci skip]"
