executor: node
parameters:
  production_branch:
    type: string
    default: "master"

steps:
  - attach_workspace:
      at: ./

  - git-set-identity

  - checkout

  - run:
      name: set release info
      # we *assume* this job is run from within the subject release branch
      command: |
        echo "export RELEASE_BRANCH_NAME=$CIRCLE_BRANCH" >> $BASH_ENV

  - git-merge-branch:
      base_branch: "develop"
      merge_branch: "$RELEASE_BRANCH_NAME"
      simulate: true

  - git-merge-branch:
      base_branch: "master"
      merge_branch: "$RELEASE_BRANCH_NAME"
      simulate: true

  - git-merge-branch:
      base_branch: "develop"
      merge_branch: "$RELEASE_BRANCH_NAME"
      trigger_ci: false

  - git-merge-branch:
      base_branch: "master"
      merge_branch: "$RELEASE_BRANCH_NAME"

  - run:
      name: bump version and document
      command: |
        git checkout master && git pull

        yarn release \
          --releaseCommitMessageFormat "chore(release): update changelog & bump version {{currentTag}}"

        git push --follow-tags origin master

  - run:
      name: remove release branch
      command: |
        git fetch --all 
        echo "deleting release branch '$RELEASE_BRANCH_NAME' ..."
        git branch -D "$RELEASE_BRANCH_NAME"
        git push origin --delete "$RELEASE_BRANCH_NAME"
